# Generated by Django 4.0 on 2021-12-19 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='accounts.account'),
        ),
    ]
