# Generated by Django 4.0 on 2021-12-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_shortener_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sulg',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
